// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBNZvAk64KswCzPqLX6Z72TXk35Nod21v0',
      authDomain: 'aquaalert-90e88.firebaseapp.com',
      databaseURL: 'https://aquaalert-90e88-default-rtdb.firebaseio.com',
      projectId: 'aquaalert-90e88',
      storageBucket: 'aquaalert-90e88.appspot.com',
      messagingSenderId: '999959773780',
      appId: '1:999959773780:web:dfac23f5459d41cec423c1',
      measurementId: 'G-2JCD1RYQSJ'
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDox_7-VNz8ybDFhwToYY86hCvmVFdz1xM',
    appId: '1:999959773780:android:f2a12d84a08a9ed5c423c1',
    messagingSenderId: '999959773780',
    projectId: 'aquaalert-90e88',
    authDomain: 'aquaalert-90e88.firebaseapp.com',
    storageBucket: 'aquaalert-90e88.appspot.com',
  );
}
